buildscript {
    dependencies {
        // Add your database extension and driver to the buildscript classpath so the plugin can see it
        classpath 'org.flywaydb:flyway-database-postgresql:13.5.0'
        classpath 'org.postgresql:postgresql:42.7.3'
    }
}
plugins {
    id 'java'
    id 'org.flywaydb.flyway' version '13.5.0'
}

group = 'eu.kaitan'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation("org.flywaydb:flyway-database-postgresql:11.3.4")
    runtimeOnly("org.postgresql:postgresql:42.7.3")
}

test {
    useJUnitPlatform()
}

flyway {
    url = 'jdbc:postgresql://localhost:5432/test-main'
    user = 'admin'
    password = ''
}